title: Getting started with wearables
hero_image: images/banner.png
description: In this resource you will learn how to create a basic piece of wearable technology
original_url: https://raspberrypi.org/learning/getting-started-with-wearables
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-1, phys-comp-1, manufacture-2, community-0
interests: wearable-technology
technologies: electronic-components
site_areas: projects
hardware: electronic-components
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Getting started with wearables
- title: Testing the FLORA board
- title: Testing the circuit
- title: Controlling the NeoPixel with code
- title: Sewing it all up
- title: Sewing the ground connection
- title: Connect the power and D6 pin
- title: What next?
